### ISSUE TITLE
NamespaceProvider.cs cannot be used on Portable Class Library

### ISSUE THREAD

**Issue by francescoargiolas** [nilproject/NiL.JS#108]
I'm using Nil.JS on a PCL Xamarin.Forms project but I can't use NamespaceProvider.cs and this make impossible to import a namespace in the javascript engine like in the example "Using NamespaceProvider.cs" .

Is possible to make a build of the package that include NamespaceProvider.cs or there is a problem of compatibility whit PCL.

**Comment by nilproject** [comment]
This is because AppDomain is not available in PCL environment. This class is used to get a list of all loaded types.
You can download NamespaceProvider.cs and modify methods `static NamespaceProvider()` and `private static void addTypes(System.Reflection.Assembly assembly)` to get types and/or assemblies from your code. It's will work, I assume.
