### ISSUE TITLE
Global object

### ISSUE THREAD

**Issue by ghost** [nilproject/NiL.JS#141]
Is it possible to define the global object (window in browsers) on a Context? I've noticed you can define the `this` object, but it seems like every Eval is within a non-global scope.

**Comment by nilproject** [comment]
For `Context` created without passing a parent context (`new Context()`), `this` is the global object. Those contexts is part of global scope. Second part is `GlobalContext`, but code cannot be evaluated inside this. If you want to define global object, you can copy implementation of [NiL.JS.Core.GlobalObject](https://github.com/nilproject/NiL.JS/blob/develop/NiL.JS/Core/GlobalObject.cs), because this class is internal. But I do not understand why this is necessary.

**Comment by ghost** [comment]
Thanks for the tips! What I'm trying to achieve is something like this:

`SomeObject.doSomething()`

Instead of what I currently have to do:

`this.SomeObject.doSomething()`

The latter implies I'm in a function scope, as I can't implicitly access members on the scope without `this`, however the former implies I'm in global scope, where I get implicit access to any object on that scope without `this`.

**Comment by ghost** [comment]
I just found one of the global context examples which helped me understand things a bit better. This seems to work well:

```csharp
      var jsCtx = new GlobalContext("global");
      var ctx = new Context(jsCtx);

      var res = ctx.Eval("console.log(this)");
```
