### ISSUE TITLE
Trying to use dynamic objects in NiL.JS

### ISSUE THREAD

**Issue by dos-ise** [nilproject/NiL.JS#144]
Hi,

I am trying to port our codebase to NiL.JS. We are using dynamic Expando Objects to store fields.
This worked quit well when using vroomJs.

When trying to use this with NiL.JS the parameter does not seems to change. 
Do you have a suggestion what I am doing wrong or if this does generally not work?

Example:
https://github.com/dos-ise/NiL.JS-Expando-Test

**Comment by nilproject** [comment]
Hi.

Thank you for choosing to use my engine.

Unfortunately, support of Expando in NiL.JS not so good, then in vroomJs. At current time, supported only `System.Dynamic.ExpandoObject`. Also you should use `JSValue.Marshal` instead of `Wrap`, because of they differ significantly.

You can look at implementation of [ExpandoObjectWrapper](https://github.com/nilproject/NiL.JS/blob/develop/NiL.JS/Core/Interop/ExpandoObjectWrapper.cs) and use it as a base for your own implementation.

**Comment by dos-ise** [comment]
Thank alot for your reponse. To make an long story short I used my expando object and repacked in an System.Dynamic.ExpandoObject. This way my code works..

`private IEnumerable<object> CreateArgs(object[] args)
    {
      foreach (var arg in args)
      {
        if (arg is IExpando)
        {
          var a = new ExpandoObject() as IDictionary<string, Object>; ;
          foreach (var field in ((Expando)arg).Fields)
          {
            a.Add(field.Key, field.Value);
          }

          yield return a;
        }
        else
        {
          yield return arg;
        }
      }
    }`

Thank you very much...
