### ISSUE TITLE
EvalAsync

### ISSUE THREAD

**Issue by shravan2x** [nilproject/NiL.JS#150]
Does it make sense to add an async version of Eval?

**Comment by nilproject** [comment]
How it should work?
You can call Eval in additional thread for async evaluation, so this does not require `EvalAsync`.
You cannot use async/yield syntax of JS in Eval directly because this is invalid. You should write a `async function`, which creates Promise on every evaluation. In NiL.JS Promise it is possible to wrap as Task and to use in await expression.
