### ISSUE TITLE
Context.Eval() with compiling

### ISSUE THREAD

**Issue by aienabled** [nilproject/NiL.JS#31]
Hello!
I can't find any way to compile code with Context.Eval().
Am I doing something wrong? I need to prepare .NET context for javascript file. First, I create a new Context, then add all dependent javascript files with Context.Eval() and then add code of the main javascript file with Context.Eval(). Then I'm able get a function from Context and invoke it. But it seems there are no optimizations/compilation done...
Is there any way for doing that using Script class (with TryCompile())?

Also I noticed that C#<->JS communitcation seems to be much slower than in Jurassic, would be like to get more advices how to improve it. The project (game) is using javascript for game logic scripts, so the fast communication is very important.

By the way, API is great, much better than Jurassic. Well done!

**Comment by nilproject** [comment]
TryCompile() is an experiment for compilation to IL. You shouldn't use it.
The main path to run a script is to create instance of Script class, because only it contains "deep optimization". 
For more performance, methods must have no more than one parameter and it mast be a class type. If you want to more parameters or transfer a value types, you should use Core.Arguments. Also, overloaded methods slower due to need to select the desired implementation

**Comment by nilproject** [comment]
May be I misunderstood, but this engine do not compile JS. It's interpreter.

**Comment by aienabled** [comment]
Thanks for response!
I was just curious if there any way to use TryCompile() for performance optimization in my case.
I will try your advices, thanks!

**Comment by nilproject** [comment]
I tried make JIT with DynamicMethod, Linq.Expressions, DynamicAssembly. All solutions was slower than interpretation.
