### ISSUE TITLE
Parser.ValidateString doesn't recognize Template literal

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [nilproject/NiL.JS#71]
For example: 
```
int i = 0;
Parser.ValidateString("`Hello World`", ref i, false); // will return false.
```

**Comment by nilproject** [comment]
It's correct because template string is more complex expression than just a string literal. `Parser.Validate<smth>(...)` will return `true` only for simple literals because they must work as fast as possible.
If you want to parse template string not as part of js-code, you should use `NiL.JS.Expressions.TemplateString.Parse(...)`.
