### ISSUE TITLE
Error Line No

### ISSUE THREAD

**Issue by wewake4** [nilproject/NiL.JS#72]
How can we get the line no of the syntax error? # #

**Comment by jsobell** [comment]
I had a very quick look and it appears the call stack does contain the character index to the item being parse when an error occurs, but I don't see it available once control returns to the calling `Eval` function.
The ideal would be to return a custom Exception object that included location information, even if it's simply the character index offset through the code string.
At the moment it's tricky because an error in the middle of something like `moment.js` can't be located without trial and error.

**Comment by jsobell** [comment]
Here's an example:
```javascript
var x = new MissingThing(1,2,3)
```
We'd normally expect get something like
```text
VM85:1 Uncaught ReferenceError: MissingThing is not defined
    at <anonymous>:1:9
```
Currently we get
```text
"ReferenceError: Variable \"MissingThing\" is not defined"
```
@nilproject , any suggestions how we might look at implementing this? We have the code and contextual information available for some of the `ExceptionHelper` methods such as `ThrowReferenceError`, but in many of the other calls we're down about 12 calls deep with no reference to the original code string.

**Comment by nilproject** [comment]
I made this while tried to understand how it can be made.
