### ISSUE TITLE
String in Log4net 

### ISSUE THREAD

**Issue by zh3305** [nilproject/NiL.JS#83]
run 
`log.Debug("successdata")`
Out
10:09:38 821|DEBUG|Thread[5] {[0, s], [1, u], [2, c], [3, c], [4, e], [5, s], [6, s], [7, d], [8, a], [9, t], [10, a]}

How Show "10:09:38 821|DEBUG|Thread[5] successdata"

**Comment by nilproject** [comment]
Try DebugFormat(...)

**Comment by RunDevelopment** [comment]
I've looked a little into it and the problem is Log4net.

Log4net tries everything to convert an object to a string and uses the GetEnumerator before ToString which is why you get each char individually.
To fix this you will have to implement IObjectRenderer for JSValue (use DefaultRenderer for reference) and then put it into the RendererMap of the current ILog.

[Here](https://github.com/nilproject/NiL.JS/files/1083057/Test.Log4Net.CS.zip) is an example implementation.

**Comment by zh3305** [comment]
Thiks
